<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Transfer_order_local_model extends MY_Model {

    public function __construct() {
        parent::__construct();
        MY_Model::set_table("tblCOM_TOL");
    }

    public function table_data($data, $type) {

        extract($data);

        $this->db->select(array(
                    'to_char("TOL_DocDate", \'mm/dd/yyyy\') as "TOL_DocDate" ',
                    'TOL_DocNo',
                    'TOL_TransferFrom',
                    'TOL_TransferTo',
                    'TOL_Company',
                    'TOL_Status',
                    'TOL_Remarks',
                    'TOL_Amount',
                    'MD5("TOL_DocNo") AS id'))
                ->order_by("DateCreated DESC")
                ->group_by("tblCOM_TOL.TOL_DocNo");


        if (isset($queries['date-from'])) {
            $this->db->where(array('DATE("TOL_DocDate") >=' => $queries['date-from']));
        }

        if (isset($queries['date-to'])) {
            $this->db->where(array('DATE("TOL_DocDate") <=' => $queries['date-to']));
        }

        if (isset($queries['location'])) {
            if ($type == 'incoming') {
                $this->db->where(
                        array(
                            'TOL_Status !='  => 'Closed',
                            'TOL_TransferTo' => $queries['location']
                        )
                );
            } else if ($type == 'outgoing') {
                $this->db->where(
                        array(
                            'TOL_Status !='    => 'Closed',
                            'TOL_TransferFrom' => $queries['location']
                        )
                );
            }
        }

        if (isset($queries['company'])) {
            if ($type == 'incoming') {
                $this->db->where(
                        array(
                            'TOL_Status !='  => 'Closed',
                            'TOL_Company' => $queries['company']
                        )
                );
            } else if ($type == 'outgoing') {
                $this->db->where(
                        array(
                            'TOL_Status !='    => 'Closed',
                            'TOL_Company' => $queries['company']
                        )
                );
            }
        }

        if (isset($queries['search'])) {
            $this->db->or_having(array(
                'LOWER(CAST("TOL_DocDate" as text)) LIKE'      => '%' . strtolower($queries['search']) . '%',
                'LOWER(CAST("TOL_DocNo" as text)) LIKE'        => '%' . strtolower($queries['search']) . '%',
                'LOWER(CAST("TOL_TransferFrom" as text)) LIKE' => '%' . strtolower($queries['search']) . '%',
                'LOWER(CAST("TOL_TransferTo" as text)) LIKE'   => '%' . strtolower($queries['search']) . '%',
                'LOWER(CAST("TOL_Company" as text)) LIKE'      => '%' . strtolower($queries['search']) . '%',
                'LOWER(CAST("TOL_Status" as text)) LIKE'       => '%' . strtolower($queries['search']) . '%',
                'LOWER(CAST("TOL_Remarks" as text)) LIKE'      => '%' . strtolower($queries['search']) . '%'));
        }

        if (isset($sorts)) {
            $res = array();
            foreach ($sorts as $key => $value) {
                $order = $value == 1 ? "ASC" : "DESC";
                array_push($res, $key . " " . $order);
            }
            $this->db->order_by(implode(",", $res));
        }

        $result = $this->db->get("tblCOM_TOL");

        if ($result->num_rows() > 0) {
            return array(
                'rows'  => $result->num_rows(),
                'count' => $result->num_rows(),
                'data'  => $result->result_array());
        } else {
            return FALSE;
        }
    }

    public function update($header, $details) {

        $status = 0;

        $header_where  = array('TOL_DocNo' => $header["TOL_DocNo"]);
        $details_where = array('TOLD_TO_DocNo' => $header["TOL_DocNo"]);

        try {
            $this->db->trans_begin();

            //  TOL_Amount is always auto generated by details
            unset($header["TOL_Amount"]);

            //  update header
            $this->db->where($header_where)->update('tblCOM_TOL', $header);

            //  reset details
            $this->db->where($details_where)->delete('tblCOM_TOLDetail');

            if ($details) {
                $reimbursement_amount = $this->_store_details($header, $details);

                //  update transfer order amount
                $new_reimbursement = array(
                    'TOL_Amount' => $reimbursement_amount
                );
                $this->db->where($header_where)->update('tblCOM_TOL', $new_reimbursement);
            }

            if ($this->db->trans_status() === FALSE) {
                $this->db->trans_rollback();
            } else {
                $this->db->trans_commit();
                $status = 1;
            }
        } catch (Exception $e) {
            $this->db->trans_rollback();
        }

        return $status;
    }

    private function _store_details($header, $details) {
        $total_amount = 0;
        foreach ($details as $value) {
            $empty = !array_filter($value);
            if (!empty($value) && !$empty) {
                $value['TOLD_TO_DocNo'] = $header['TOL_DocNo'];

                $total_amount += $value["TOLD_Total"];

                $this->db->insert('tblCOM_TOLDetail', add_data($value));
            }
        }

        return $total_amount;
    }

}
